Fix: correctly escape locale-gen script

diff --git a/modules/999-replace-locale-gen.yml b/modules/999-replace-locale-gen.yml
--- a/modules/999-replace-locale-gen.yml
+++ b/modules/999-replace-locale-gen.yml
@@ -2,60 +2,60 @@ name: replace-locale-gen
 type: shell
 commands:
 - |
-  echo <<EOF > /usr/sbin/locale-gen
-  #!/bin/sh
-
-  set -e
-
-  LOCALEGEN=/etc/locale.gen
-  LOCALES=/usr/share/i18n/locales
-  USER_LOCALES=/usr/local/share/i18n/locales
-  LOCALEDIR=/etc/locales
-
-  [ -s "$LOCALEGEN" ] || exit 0
-
-  [ "$1" = '--keep-existing' ] && KEEP=1 || KEEP=0
-
-  # Remove old locale-archive before generating new locale data
-  [ "$KEEP" -eq 0 ] && rm -rf /usr/lib/locale/locale-archive || :
-
-  # Create locale directory if non-existent
-  [ ! -d $LOCALEDIR ] && mkdir -p $LOCALEDIR || :
-
-  umask 022
-
-  is_entry_ok() {
-      if [ -z "$locale" ] || [ -z "$charset" ]; then
-          echo "error: Bad entry '$locale $charset'"
-          return 1
-      fi
-  }
-
-  echo "Generating locales (this might take a while)..."
-  while read -r locale charset; do
-      if [ -z "$locale" ] || [ "${locale#\#}" != "$locale" ]; then continue; fi
-      is_entry_ok || continue
-
-      if [ "$KEEP" -eq 1 ] && PERL_BADLANG=0 perl -MPOSIX -e 'exit 1 unless setlocale(LC_ALL, $ARGV[0])' "$locale"; then continue; fi
-
-      locale_base="${locale%%.*}"
-      locale_base="${locale_base%%@*}"
-      locale_at="${locale#*@}"
-      [ "$locale_at" = "$locale" ] && locale_at= || locale_at="@$locale_at"
-      printf "  %s.%s%s..." "$locale_base" "$charset" "$locale_at"
-
-      if [ -e "$USER_LOCALES/$locale" ]; then
-          input="$USER_LOCALES/$locale"
-      elif [ -e "$LOCALES/$locale" ]; then
-          input="$locale"
-      else
-          input="$locale_base$locale_at"
-          if [ -e "$USER_LOCALES/$input" ]; then
-              input="$USER_LOCALES/$input"
-          fi
-      fi
-      localedef -i "$input" -c -f "$charset" -A /usr/share/locale/locale.alias "${LOCALEDIR}/${locale}" || :
-      echo " done"
-  done < "$LOCALEGEN"
-  echo "Generation complete."
-  EOF
+  echo '\
+  #!/bin/sh\n\
+  \n\
+  set -e\n\
+  \n\
+  LOCALEGEN=/etc/locale.gen\n\
+  LOCALES=/usr/share/i18n/locales\n\
+  USER_LOCALES=/usr/local/share/i18n/locales\n\
+  LOCALEDIR=/etc/locales\n\
+  \n\
+  [ -s "$LOCALEGEN" ] || exit 0\n\
+  \n\
+  [ "$1" = '--keep-existing' ] && KEEP=1 || KEEP=0\n\
+  \n\
+  # Remove old locale-archive before generating new locale data\n\
+  [ "$KEEP" -eq 0 ] && rm -rf /usr/lib/locale/locale-archive || :\n\
+  \n\
+  # Create locale directory if non-existent\n\
+  [ ! -d $LOCALEDIR ] && mkdir -p $LOCALEDIR || :\n\
+  \n\
+  umask 022\n\
+  \n\
+  is_entry_ok() {\n\
+      if [ -z "$locale" ] || [ -z "$charset" ]; then\n\
+          echo "error: Bad entry '$locale $charset'"\n\
+          return 1\n\
+      fi\n\
+  }\n\
+  \n\
+  echo "Generating locales (this might take a while)..."\n\
+  while read -r locale charset; do\n\
+      if [ -z "$locale" ] || [ "${locale#\#}" != "$locale" ]; then continue; fi\n\
+      is_entry_ok || continue\n\
+  \n\
+      if [ "$KEEP" -eq 1 ] && PERL_BADLANG=0 perl -MPOSIX -e 'exit 1 unless setlocale(LC_ALL, $ARGV[0])' "$locale"; then continue; fi\n\
+  \n\
+      locale_base="${locale%%.*}"\n\
+      locale_base="${locale_base%%@*}"\n\
+      locale_at="${locale#*@}"\n\
+      [ "$locale_at" = "$locale" ] && locale_at= || locale_at="@$locale_at"\n\
+      printf "  %s.%s%s..." "$locale_base" "$charset" "$locale_at"\n\
+  \n\
+      if [ -e "$USER_LOCALES/$locale" ]; then\n\
+          input="$USER_LOCALES/$locale"\n\
+      elif [ -e "$LOCALES/$locale" ]; then\n\
+          input="$locale"\n\
+      else\n\
+          input="$locale_base$locale_at"\n\
+          if [ -e "$USER_LOCALES/$input" ]; then\n\
+              input="$USER_LOCALES/$input"\n\
+          fi\n\
+      fi\n\
+      localedef -i "$input" -c -f "$charset" -A /usr/share/locale/locale.alias "${LOCALEDIR}/${locale}" || :\n\
+      echo " done"\n\
+  done < "$LOCALEGEN"\n\
+  echo "Generation complete."\n\
+  ' > /usr/sbin/locale-gen
